# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaverApiErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_seq', models.IntegerField(blank=True, null=True)),
                ('api_error_code', models.CharField(blank=True, max_length=10, null=True)),
                ('api_error_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_api_error_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaverApiStatus',
            fields=[
                ('api_seq', models.AutoField(primary_key=True, serialize=False)),
                ('api_type', models.CharField(blank=True, max_length=20, null=True)),
                ('api_status', models.IntegerField(blank=True, null=True)),
                ('api_error_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'naver_api_status',
                'managed': False,
            },
        ),
    ]
